name: PrisonRanks
version: "${version}"
main: tech.mcprison.prison.ranks.plugins.RanksSpigot
depend: [Prison]
description: A ranks module for Prison.
author: The MC-Prison Team
website: https://mc-prison.tech

permissions:
  ranks.user:
    description: Allows users to see the ranks and rank up.
    default: true

  ranks.command:
    description: Access to the /ranks command command.

  ranks.ladder:
    description: Access to the /ranks ladder command.

  ranks.info:
    description: Access to the /ranks info command.

  ranks.list:
    description: Access to the /ranks list command.

  ranks.create:
    description: Access to the /ranks create command.

  ranks.delete:
    description: Access to the /ranks delete command.

  ranks.admin:
    description: Contains all the commands reserved for admins.
    default: op
    children:
      ranks.user: true
      ranks.command: true
      ranks.ladder: true
      ranks.info: true
      ranks.list: true
      ranks.create: true
      ranks.delete: true